### ISSUE TITLE
Add an open source license?

### ISSUE THREAD

**Issue by jasonblais** [Better-Boy/UMatter#1]
Thanks for sharing this project and submitting it to [Mattermost Bot Hackfest](https://www.hackerearth.com/challenges/hackathon/mattermost-bot-hackfest/)!

Would you consider adding an MIT LICENSE.txt file?

To do so, in GitHub you can hit "Create new file" and name a file `LICENSE.txt`

![image](https://cloud.githubusercontent.com/assets/177788/19657017/36238482-99d7-11e6-9fd0-f507970891c7.png)

This will prompt GitHub to offer a license template: 

![image](https://cloud.githubusercontent.com/assets/177788/19657044/5a2d8b66-99d7-11e6-8164-ac7f90b10646.png)

If you add the MIT license, it would make it easy for the open source community to contribute and use your work. It'll be extra points during the hackathon evaluation process as well ;) 

Thanks kindly for your consideration.

**Comment by Better-Boy** [comment]
Oops, I forgot to add one. Added MIT License
Thanks @jasonblais 
Hence, I'll be closing this issue

**Comment by Better-Boy** [comment]
License added
